default_platform(:android)

platform :android do
  desc "lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:673221858767:android:c06ed64f5ffd05520c6eba",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "amr.elzorkany97@gmail.com",
      release_notes: "Release notes using fastlane"
    )
  end
end
