name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

#لما اعمل بوش او بول ريكويست نفذ الوظائف دى     
jobs:
  Build: 
    runs-on: ubuntu-latest


    steps:
      - name: Checkout my repo code   #optional naming describe what action will do , get code from my repo
        #عبارة عن امر جاهز بينفذ عملية معينة على جيت هب
        uses: actions/checkout@v3  #command in github action , to checkout my repo code

      - name: Set up java 17  #because of i want to "release android app" so i will need java
        uses: actions/setup-java@v3  
          with:
            distribution: 'temurin' #there are more than one distribution in java but 'temurin' is more stable
            java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          #channel: stable

      # - name: Setup Ruby        #must install ruby to use fastlane
      #   uses: ruby/setup-ruby@v1
      #   with:      
      #     ruby-version: "3.3.0"  #latest version of ruby
      #     bundler-cache: true    #make workflow faster by caching dependencies
      #     working-directory: android   # place where ruby will be installed ,its looklike i write "cd android" in terminal when i run this action

      # - name: Build and Distribute App
      #   env:
      #     FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}  #get secret from github secret
      #   run: |
      #     bundle exec fastlane android firebase_distribution  
      #   working-directory: android
      #line 37 " bundle exec" make workflow faster ,this name "firebase_distribution" is not optional must be same as lane name in Fastfile
      #must change version in yaml when i push
      - name: Build and Distribute App
        run: flutter run --no-enable-impeller -t lib/main_development.dart

      - name: Upload APK
        uses: actions/upload-artifact@v3   
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk